import A from '../assets/ui/1.png'
import B from '../assets/ui/2.png'
import C from '../assets/ui/3.png'
import D from '../assets/ui/4.png'
import E from '../assets/ui/5.png'
import F from '../assets/ui/6.png'
import G from '../assets/ui/7.png'
import H from '../assets/ui/8.png'
import I from '../assets/ui/9.png'
import J from '../assets/ui/10.png'
import K from '../assets/ui/11.png'
import L from '../assets/ui/12.png'
import M from '../assets/ui/13.png'
import N from '../assets/ui/14.png'
import O from '../assets/ui/15.png'
import PQ from '../assets/ui/16.png'
import R from '../assets/ui/17.png'
import S from '../assets/ui/18.png'
import T from '../assets/ui/19.png'
import U from '../assets/ui/20.png'
import V from '../assets/ui/21.png'
import W from '../assets/ui/22.png'
import X from '../assets/ui/23.png'
import Y from '../assets/ui/24.png'
import Z from '../assets/ui/25.png'
import AA from '../assets/ui/26.png'
import BB from '../assets/ui/27.png'
import CC from '../assets/ui/28.png'
import DD from '../assets/ui/29.png'
import EE from '../assets/ui/30.png'
import FF from '../assets/ui/31.png'
import GG from '../assets/ui/32.png'
import HH from '../assets/ui/33.png'
import II from '../assets/ui/34.png'
import JJ from '../assets/ui/35.png'
import KK from '../assets/ui/36.png'
import LL from '../assets/ui/37.png'

export {
    A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,PQ,R,S,T,U,V,W,X,Y,Z,AA,BB,CC,DD,EE
    ,FF,GG,HH,II,JJ,KK,LL
}